// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SparseColDeltaCor
arma::sp_mat SparseColDeltaCor(const arma::sp_mat& e, const arma::sp_mat& d, const arma::sp_mat& knn);
RcppExport SEXP _compact_SparseColDeltaCor(SEXP eSEXP, SEXP dSEXP, SEXP knnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type e(eSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type knn(knnSEXP);
    rcpp_result_gen = Rcpp::wrap(SparseColDeltaCor(e, d, knn));
    return rcpp_result_gen;
END_RCPP
}
// SparseEmbArrows
arma::mat SparseEmbArrows(const arma::mat& emb, const arma::sp_mat& tp, double arrowScale, int nthreads);
RcppExport SEXP _compact_SparseEmbArrows(SEXP embSEXP, SEXP tpSEXP, SEXP arrowScaleSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type emb(embSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type arrowScale(arrowScaleSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(SparseEmbArrows(emb, tp, arrowScale, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_compact_SparseColDeltaCor", (DL_FUNC) &_compact_SparseColDeltaCor, 3},
    {"_compact_SparseEmbArrows", (DL_FUNC) &_compact_SparseEmbArrows, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_compact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
